### ISSUE TITLE
The format specified in the comment hint for `overrideParameters` does not work

### ISSUE THREAD

**Issue by BeigeBadger** [whiteducksoftware/azure-arm-action#4]
## Describe the bug
The `overrideParameters` parameter has the following comment intended to provide guidance to users on how it should be used:

```
# Specify either path to the Azure Resource Manager override parameters file or pass them as 'key1=value1;key2=value2;...'.
```

However, the format of `key1=value1;key2=value2;` is rejected by the Azure Resource Manager (ARM) Template Deployment task with an invalid pair error.

In order to rectify this I had to use the multi-line format outlined in the [Advanced.md](https://github.com/whiteducksoftware/azure-arm-action/blob/master/examples/Advanced.md) file provided as part of this repo:

```
overrideParameters: |
    adminUsername=matt-github
    adminPasswordOrKey=matt-github-pass
    dnsLabelPrefix=ghactiontest
```

## To Reproduce
1. Create a new repo in GitHub or reuse an existing one.
2. Add the ARM template from [here](https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-simple-linux/azuredeploy.json) to the root of the repo.
3. Setup a new GitHub Action for the repo.
4. Add this task.
5. Configure the `overrideParameters` option as follows: 'adminUsername=matt-github;adminPasswordOrKey=matt-github-pass;dnsLabelPrefix=ghactiontest;'
6. Commit the changes
7. The pipeline will fail.

## Expected behavior
The pipeline should succeed as the format matches that specified in the hint comment.

## Screenshots/Logs

Example Action:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Azure Resource Manager (ARM) Template Deployment
      uses: whiteducksoftware/azure-arm-action@v3.1
      with:
        # Paste output of `az ad sp create-for-rbac -o json` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.GH_ACTIONS_SP }}
        # Provide the name of a resource group.
        resourceGroupName: rg-github-actions-test
        # Specify the path to the Azure Resource Manager template.
        templateLocation: ./azuredeploy.json
        # Specifies the name of the resource group deployment to create.
        deploymentName: gh-action-deployment
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
        deploymentMode: Incremental
        # Specify either path to the Azure Resource Manager override parameters file or pass them as 'key1=value1;key2=value2;...'.
        overrideParameters: 'adminUsername=matt-github;adminPasswordOrKey=matt-github-pass;dnsLabelPrefix=ghactiontest;'
```
Logs:

```
Run whiteducksoftware/azure-arm-action@v3.1
  with:
    creds: ***
    resourceGroupName: rg-github-actions-test
    templateLocation: ./azuredeploy.json
    deploymentName: gh-action-deployment
    deploymentMode: Incremental
    overrideParameters: adminUsername=matt-github;adminPasswordOrKey=matt-github-pass;dnsLabelPrefix=ghactiontest;
/usr/bin/docker run --name whiteduckazurearmactionv31_abffbc --label 8118cb --workdir /github/workspace --rm -e INPUT_CREDS -e INPUT_RESOURCEGROUPNAME -e INPUT_TEMPLATELOCATION -e INPUT_DEPLOYMENTNAME -e INPUT_DEPLOYMENTMODE -e INPUT_OVERRIDEPARAMETERS -e INPUT_PARAMETERS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/GHActionsTest/GHActionsTest":"/github/workspace" whiteduck/azure-arm-action:v3.1
time="2020-08-06T21:46:19Z" level=error msg="failed to load options: failed to parse inputs: Custom parser error: Found invalid pair, expected KEY=VALUE got adminUsername=matt-github;adminPasswordOrKey=matt-github-pass;dnsLabelPrefix=ghactiontest;"
```

## Additional context
I am new to GitHub actions but have experience with various other CI/CD platforms such as Azure DevOps, TeamCity, Octopus Deploy, and AppVeyor so maybe this is something I am missing.

I also noted that the comment for the `parameters` property has the same comment but I haven't used it so it may or may not have the same issue. It could be confusing for new users as to why this doesn't work.
