### ISSUE TITLE
Passing multiple parameters to action

### ISSUE THREAD

**Issue by aksh-h** [whiteducksoftware/azure-arm-action#5]
Hi there,

I'm not finding a way to pass multiple parameters to GitHub action to deploy ARM template.
I've some parameters to be picked up from ```template.parameters.json``` and other should be passed inline to the action. 

I tried something like this, which didn't work.

```YAML
- name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: YAML 
          region: Central India
          template: ./ARMTemplates/azuredeploy.json
          #parameters: ./ARMTemplates/azuredeploy.parameters.json
          parameters: ./ARMTemplates/azuredeploy.parameters.json,WebsiteName=abc893eyq,ServerName=server1s38,HostingPlanName=abce2e
```
