### ISSUE TITLE
Failed to authenticate with azure

### ISSUE THREAD

**Issue by dalmasj** [whiteducksoftware/azure-arm-action#8]
Hello,

We have an issue when using `v3.3` with the following error : 
`level=error msg="Failed to authenticate with azure: Invoking Azure CLI failed with the following error: "`

Before this action we login to azure with `Azure/login`  and the login was successfull
The secret for login is like `{ "clientId": "***", "clientSecret": "***", "subscriptionId": "***", "tenantId": "***"}`

Do you have any idea what is wrong ?
Thank you

**Comment by nmeisenzahl** [comment]
@StiviiK can you please review this issue.

**Comment by StiviiK** [comment]
Hi @dalmasj, may you please provide your workflow file? So I can look into this issue further.

**Comment by dalmasj** [comment]
Hi,
My workflow file is like that:

```
  on: 
    push:
      branches: [ workflowconfiguration ]
  env:
    templatePath: ARMTemplateForFactory.json
    resourceGroupName: xxxx
    factoryName: xxxxx
    xxxx_connectionString: xxx
  
  jobs:
    build-and-deploy:
      runs-on: ubuntu-18.04
      steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
        
      - name: Login via Az Module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDS}}
          enable-AzPSSession: true
            
      - name: Deploy arm template adf
        uses: whiteducksoftware/azure-arm-action@v3.3
        with:
          resourceGroupName: ${{env.resourceGroupName }}
          templateLocation: ${{env.templatePath }}
          deploymentName: "datafactorydeployment"
          overrideparameters:
                            factoryName=${{env.factoryName}}
                            xxxx_connectionString=${{env.xxxx_connectionString}}

```
